name: mChat
version: '1.0'
main: mm.min1moys.mchat.mChat
api-version: '1.21.1'
softdepend: [PlaceholderAPI, Vault]
permissions:
  mchat.reload:
    description: Allows /mchat reload command.
    default: false
  mchat.bypass:
    description: Allows bypassing global chat requirements
    default: false
  mchat.local:
    description: Allows local chat.
    default: true
  mchat.global:
    description: Allows global chat.
    default: true
commands:
  mchat:
    description: Used to reload configuration